### ISSUE TITLE
lora-packet-forwarder-utils depencies...

### ISSUE THREAD

**Issue by pacmenDE** [xueliu/lora-feed#11]
Hi, there are some depnecies issues for pkt_forwader utils...
:-)

 * check_data_file_clashes: Package lora-packet-forwarder-utils wants to install file /home/patrik/openwrt1806/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/root-brcm2708/usr/sbin/util_tx_test
        But that file is already provided by package  * libloragw-utils
 * opkg_install_cmd: Cannot install package lora-packet-forwarder-utils.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/patrik/openwrt

**Comment by xueliu** [comment]
Yes. It is a name conflict. The program util_tx_test exist in both lora-gateway-hal and lora-packet-forwarder.
