### ISSUE TITLE
basicstation failed to compile

### ISSUE THREAD

**Issue by timothybean** [xueliu/lora-feed#15]
openwrt/build_dir/target-mipsel_24kc_musl/basicstation-2.0.3/src/sx1301conf.c: In function 'sx1301conf_start':
openwrt/build_dir/target-mipsel_24kc_musl/basicstation-2.0.3/src/sx1301conf.c:436:5: error: 'lgwx_device_mode' undeclared (first use in this function); did you mean 'J_device_mode'?
     lgwx_device_mode = sys_deviceMode;
     ^~~~~~~~~~~~~~~~
     J_device_mode

Any thoughts on how to resolve this?

Thanks

**Comment by xueliu** [comment]
Hello,

I think this compile error is caused by that basicstation patch is not applied in lora-gateway-hal.
Please refer README to update the lora-gateway-hal.
