### ISSUE TITLE
How to build cockroachDB?

### ISSUE THREAD

**Issue by guo652917087** [xueliu/lora-feed#16]
lorawan-stack uses cockroach database, how to compile this database in openWRT environment? There is also a front end of lorawan-stack (compiled with ./mage js: build) that is supported?

**Comment by xueliu** [comment]
Hello,

As far as I know, cockroach database is not supported by OpenWRT master. I will try to add it to this feed.

Currently the front-end of lorawan-stack can not be compiled. I will try to fix it when I have free time.

Regards

**Comment by guo652917087** [comment]
Hi,@xueliu 
I appreciate your reply very much, waiting for your good news

**Comment by xueliu** [comment]
I did not make any progress. I will open it again when I found some news.
