### ISSUE TITLE
luci-app-pkg-fwd has all configuration twice, this breaks the apply

### ISSUE THREAD

**Issue by nielskoot** [xueliu/lora-feed#18]
I think the last commit on the luci app (https://github.com/xueliu/lora-feed/commit/90ac0191c7bad95e98a310c24cd779b820a3a432) accidentally duplicated most of the content instead of just adding RSSI target and RSSI offset. This causes the GUI to have most settings twice (very confusing) and breaks the apply due to errors.

**Comment by xueliu** [comment]
Thanks for the comment. You are right.
I fix the problem in e701c85df2ea948a7b80de4ac61121a609767700
