### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 1988liuwu** [xueliu/lora-feed#4]
the following is the log detail, and you help find out what's the problem?? i make it at opnwrt-master version....

make[7]: Entering directory '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/deps/mbedtls/platform-openwrt/library'
  AR    libmbedcrypto.a
make[7]: NO-TOOLCHAIN-FOUND-ar: Command not found
Makefile:139: recipe for target 'libmbedcrypto.a' failed
make[7]: *** [libmbedcrypto.a] Error 127
make[7]: Leaving directory '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/deps/mbedtls/platform-openwrt/library'
Makefile:18: recipe for target 'lib' failed
make[6]: *** [lib] Error 2
make[6]: Leaving directory '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/deps/mbedtls/platform-openwrt'
makefile:18: recipe for target 'platform-openwrt/library/libmbedtls.a' failed
make[5]: *** [platform-openwrt/library/libmbedtls.a] Error 2
make[5]: Leaving directory '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/deps/mbedtls'
makefile:41: recipe for target 'deps/mbedtls' failed
make[4]: *** [deps/mbedtls] Error 2
make[4]: Leaving directory '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2'
Makefile:52: recipe for target '/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/.built' failed
make[3]: *** [/home/vae/openwrt/openwrt-master/build_dir/target-mips_24kc_musl/basicstation-2.0.2/.built] Error 2
make[3]: Leaving directory '/home/vae/openwrt/openwrt-master/feeds/lora/basicstation'
time: package/feeds/lora/basicstation/compile#0.16#0.03#0.72
package/Makefile:107: recipe for target 'package/feeds/lora/basicstation/compile' failed
make[2]: *** [package/feeds/lora/basicstation/compile] Error 2
make[2]: Leaving directory '/home/vae/openwrt/openwrt-master'
package/Makefile:103: recipe for target '/home/vae/openwrt/openwrt-master/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/vae/openwrt/openwrt-master/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/vae/openwrt/openwrt-master'
/home/vae/openwrt/openwrt-master/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by xueliu** [comment]
Hello,

Please have a look at my post https://clockworkbird9.wordpress.com/2019/03/12/a-simple-test-of-the-brand-new-lora-packet-forwarder-basicstation-in-openwrt/.

I use a "dirty" way to compile the basicstation
